# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_components.py; do not edit.
from genro_builders.builder import element


class FormDeclarations:
    """Alpha component declarations; runtime owns values and binding."""

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-form'})
    def form(self, **kwargs): ...
