# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_components.py; do not edit.
from genro_builders.builder import element


class InputDeclarations:
    """Alpha component declarations; runtime owns values and binding."""

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-textbox'})
    def textBox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-textboxarea'})
    def textBoxArea(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-filteringselect'})
    def filteringSelect(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-dbselect'})
    def dbSelect(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-combobox'})
    def comboBox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-passwordbox'})
    def passwordbox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-numbertextbox'})
    def numberTextBox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-datetextbox'})
    def dateTextBox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-timetextbox'})
    def timeTextBox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-horizontalslider'})
    def horizontalSlider(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-verticalslider'})
    def verticalSlider(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-checkbox'})
    def checkbox(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-datecalendar'})
    def dateCalendar(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-colorpicker'})
    def colorpicker(self, **kwargs): ...
