# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_components.py; do not edit.
from genro_builders.builder import element


class LayoutDeclarations:
    """Alpha component declarations; runtime owns values and binding."""

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-formlet'})
    def formlet(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-panel'})
    def panel(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-box'})
    def box(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-bordercontainer'})
    def borderContainer(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-tabcontainer'})
    def tabContainer(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-tab'})
    def tab(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-contentpane'})
    def contentPane(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-stackcontainer'})
    def stackContainer(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-stackbuttons'})
    def stackButtons(self, **kwargs): ...

    @element(sub_tags='*', _meta={'dataScope': True, 'webcomponent': True, 'render_tag': 'gnr-groupbox'})
    def groupBox(self, **kwargs): ...
