# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
# Generated by scripts/generate_components.py; do not edit.
from genro_builders.builder import element


class AdjacentWidgetDeclarations:
    """Alpha component declarations; runtime owns values and binding."""

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-copybutton'})
    def copyButton(self, **kwargs): ...

    @element(sub_tags='*', _meta={'webcomponent': True, 'render_tag': 'gnr-palette'})
    def palette(self, **kwargs): ...

    @element(sub_tags='', _meta={'dataWidget': True, 'webcomponent': True, 'render_tag': 'gnr-storetree'})
    def storeTree(self, **kwargs): ...

    @element(sub_tags='', _meta={'webcomponent': True, 'render_tag': 'gnr-codemirror'})
    def codeMirror(self, **kwargs): ...
