import {test, expect} from '@playwright/test';

const url = process.env.GRAMLOT_CHART_URL || 'http://127.0.0.1:8054/page/chart/';
test('Python chartBox shares grid data, selection and live palette structure', async ({page}) => {
    const errors=[]; page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    const chart=page.locator('gnr-chart'), grid=page.locator('gnr-grid');
    await expect(chart.locator('rect')).toHaveCount(6);
    await grid.locator('[data-row-key="feb"]').click();
    await expect(chart.locator('[data-row-key="feb"]')).toHaveAttribute('aria-pressed','true');
    await chart.locator('[data-row-key="apr"]').click();
    await expect(grid.locator('[data-row-key="apr"]')).toHaveAttribute('aria-selected','true');
    await page.locator('gnr-grid [data-row-key="jan"] .cell').nth(1).dblclick();
    const input=page.locator('gnr-grid gnr-numbertextbox input');
    await input.fill('310'); await input.press('Enter');
    await expect(chart.locator('[data-row-key="jan"]')).toHaveAttribute('data-value','310');
    await expect(grid.locator('[data-row-key="jan"]')).toContainText('310');
    await page.getByRole('button',{name:'Add July',exact:true}).click();
    await expect(chart.locator('rect')).toHaveCount(7);
    await chart.locator('[data-row-key="jul"]').click();
    await page.getByRole('button',{name:'Remove July',exact:true}).click();
    await expect(chart.locator('rect')).toHaveCount(6);
    await expect(chart.locator('[aria-pressed="true"]')).toHaveCount(0);
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    const palette=page.locator('gnr-palette').first();
    await expect(palette).toBeVisible();
    await palette.locator('gnr-textbox[lbl="Title"] input').fill('Monthly costs');
    await palette.locator('gnr-textbox[lbl="Title"] input').press('Tab');
    await expect(chart.locator('svg')).toHaveAttribute('aria-label','Monthly costs');
    const field=palette.locator('gnr-checkboxtext');
    await field.locator('input').first().click();
    await field.getByRole('checkbox',{name:'Cost',exact:true}).check();
    await field.getByRole('checkbox',{name:'Revenue',exact:true}).uncheck();
    await page.keyboard.press('Escape');
    await expect(chart.locator('[data-row-key="jan"]')).toHaveAttribute('data-value','75');
    await palette.locator('gnr-textbox[lbl="Bar colour"] input').fill('#b45309');
    await palette.locator('gnr-textbox[lbl="Bar colour"] input').press('Tab');
    await expect(chart.locator('rect').first()).toHaveAttribute('fill','#b45309');
    await palette.locator('gnr-checkbox input').uncheck();
    await expect(chart.locator('.value')).toHaveCount(0);
    await palette.getByRole('button',{name:'Close palette'}).click();
    await expect(palette).toBeHidden();
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    await expect(palette.locator('gnr-textbox[lbl="Title"] input')).toHaveValue('Monthly costs');
    await expect(palette.locator('gnr-checkbox input')).not.toBeChecked();
    expect(errors).toEqual([]);
});

test('chart resizes without losing selected record', async ({page}) => {
    await page.setViewportSize({width:1400,height:950});await page.goto(url);
    const chart=page.locator('gnr-chart');
    await expect(chart.locator('rect')).toHaveCount(6);
    await chart.locator('[data-row-key="mar"]').click();
    const before=await chart.locator('svg').getAttribute('viewBox');
    // Resize the chart's actual layout container (the source panel has a splitter).
    await chart.evaluate(el => {el.parentElement.style.width='280px';});
    await expect(chart.locator('svg')).not.toHaveAttribute('viewBox',before);
    await expect(chart.locator('[data-row-key="mar"]')).toHaveAttribute('aria-pressed','true');
});

test('pie palette option retains grid selection and updates proportions', async ({page}) => {
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(url);
    const chart=page.locator('gnr-chart');
    await expect(chart.locator('rect.bar')).toHaveCount(6);
    await page.locator('gnr-grid [data-row-key="feb"]').click();
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    const palette=page.locator('gnr-palette').first();
    const type=palette.locator('gnr-filteringselect[lbl="Chart type"]');
    await type.getByRole('button',{name:'Show options'}).click();
    await type.getByRole('option',{name:'Pie',exact:true}).click();
    await expect(chart.locator('path.slice')).toHaveCount(6);
    await expect(chart.locator('path.slice[data-row-key="feb"]')).toHaveAttribute('aria-pressed','true');
    await palette.getByRole('button',{name:'Close palette'}).click();
    await chart.locator('path.slice[data-row-key="apr"]').focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('gnr-grid [data-row-key="apr"]')).toHaveAttribute('aria-selected','true');
    const before=await chart.locator('path.slice[data-row-key="jan"]').getAttribute('d');
    await page.locator('gnr-grid [data-row-key="jan"] .cell').nth(1).dblclick();
    const input=page.locator('gnr-grid gnr-numbertextbox input');
    await input.fill('350');await input.press('Enter');
    await expect(chart.locator('path.slice[data-row-key="jan"]')).not.toHaveAttribute('d',before);
    await expect(chart.locator('path.slice[data-row-key="jan"]')).toHaveAttribute('data-value','350');
    await page.getByRole('button',{name:'Add July',exact:true}).click();await expect(chart.locator('path.slice')).toHaveCount(7);
    await page.getByRole('button',{name:'Remove July',exact:true}).click();await expect(chart.locator('path.slice')).toHaveCount(6);
    await page.screenshot({path:'temp/chartbox-pie.png',fullPage:true});
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    await type.getByRole('button',{name:'Show options'}).click();await type.getByRole('option',{name:'Bars',exact:true}).click();
    await expect(chart.locator('rect.bar')).toHaveCount(6);await expect(chart.locator('path.slice')).toHaveCount(0);
    expect(errors).toEqual([]);
});

test('cell drafts and Escape do not change chart data', async ({page}) => {
    await page.goto(url);
    const chart=page.locator('gnr-chart');
    const cell=page.locator('gnr-grid [data-row-key="jan"] .cell').nth(1);
    await expect(chart.locator('rect.bar[data-row-key="jan"]')).toHaveAttribute('data-value','120');
    await cell.dblclick();
    const input=page.locator('gnr-grid gnr-numbertextbox input');
    await input.fill('999');
    await expect(chart.locator('rect.bar[data-row-key="jan"]')).toHaveAttribute('data-value','120');
    await input.press('Escape');
    await expect(cell).toHaveText('120');
    await expect(chart.locator('rect.bar[data-row-key="jan"]')).toHaveAttribute('data-value','120');
});


test('multiple series stay linked to editable grid and survive pie switch',async({page})=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(url);
    const chart=page.locator('gnr-chart');
    await expect(chart.locator('rect.bar')).toHaveCount(6);
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    const palette=page.locator('gnr-palette').first(), multi=palette.locator('gnr-checkboxtext');
    await multi.locator('input').first().click();
    await expect(multi.getByRole('checkbox',{name:'Revenue',exact:true})).toBeChecked();
    await multi.getByRole('checkbox',{name:'Cost',exact:true}).check();
    await expect(chart.locator('rect.bar')).toHaveCount(12);
    await page.keyboard.press('Escape');
    await palette.getByRole('button',{name:'Close palette'}).click();
    const costs=chart.locator('rect.bar[data-row-key="jan"][data-series="cost"]');
    const revenue=chart.locator('rect.bar[data-row-key="jan"][data-series="revenue"]');
    expect(await costs.getAttribute('x')).not.toBe(await revenue.getAttribute('x'));
    await costs.click();
    await expect(page.locator('gnr-grid [data-row-key="jan"]')).toHaveAttribute('aria-selected','true');
    await expect(revenue).toHaveAttribute('aria-pressed','true');
    await page.locator('gnr-grid [data-row-key="jan"] .cell').nth(2).dblclick();
    const input=page.locator('gnr-grid gnr-numbertextbox input');await input.fill('95');await input.press('Enter');
    await expect(costs).toHaveAttribute('data-value','95');
    await expect(revenue).toHaveAttribute('data-value','120');
    await page.screenshot({path:'/tmp/chart-multiple.png',fullPage:true});
    await page.getByRole('button',{name:'Configure chart',exact:true}).click();
    const type=palette.locator('gnr-filteringselect[lbl="Chart type"]');
    await type.getByRole('button',{name:'Show options'}).click();await type.getByRole('option',{name:'Pie',exact:true}).click();
    await expect(chart.locator('path.slice')).toHaveCount(6);
    await type.getByRole('button',{name:'Show options'}).click();await type.getByRole('option',{name:'Bars',exact:true}).click();
    await expect(chart.locator('rect.bar')).toHaveCount(12);
    await multi.locator('input').first().click();
    await multi.getByRole('checkbox',{name:'Cost',exact:true}).uncheck();
    await multi.getByRole('checkbox',{name:'Revenue',exact:true}).uncheck();
    await expect(chart.locator('.error')).toBeVisible();
    await multi.getByRole('checkbox',{name:'Revenue',exact:true}).check();
    await expect(chart.locator('rect.bar')).toHaveCount(6);await expect(chart.locator('.error')).toBeHidden();
    expect(errors).toEqual([]);
});
