import {test,expect} from '@playwright/test';
test('real Genropy selection reaches shared Gramlot store and grid',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 test.skip(!process.env.GRAMLOT_STATES_URL, 'Requires the optional live GenroPy example host');
 await page.goto(process.env.GRAMLOT_STATES_URL);
 await expect(page.locator('.example-live')).toBeVisible();
 await expect(page.locator('.example-live')).toContainText('8 states loaded',{timeout:20000});
 await expect(page.locator('gnr-grid').first().locator('[data-row-key]')).toHaveCount(8);
 await expect(page.locator('gnr-grid').first()).toContainText('New South Wales');
 await expect(page.locator('.cm-editor')).toBeVisible();
 await page.locator('gnr-grid').first().locator('[data-row-key="NSW"]').click();
 const localities=page.locator('gnr-grid').nth(1);
 const customers=page.locator('gnr-grid').nth(2);
 await expect(page.locator('.example-live')).toContainText('customers in NSW');
 expect(await customers.evaluate(g=>g.collectionStore().getItems().every(n=>n.getAttr('state')==='NSW'))).toBe(true);
 await expect.poll(()=>localities.evaluate(g=>g.collectionStore().metadata.totalrows || 0)).toBeGreaterThan(0);
 expect(await localities.evaluate(g=>g.collectionStore().getItems().every(n=>n.getAttr('state')==='NSW'))).toBe(true);
 await expect(page.locator('.example-live')).toContainText('localities in NSW');
 await page.locator('gnr-grid').first().locator('[data-row-key="VIC"]').click();
 await expect(page.locator('.example-live')).toContainText('localities in VIC');
 await expect(page.locator('.example-live')).toContainText('customers in VIC');
 expect(await customers.evaluate(g=>g.collectionStore().getItems().every(n=>n.getAttr('state')==='VIC'))).toBe(true);
 await customers.scrollIntoViewIfNeeded();
 await expect(customers).toBeVisible();
 expect(await localities.evaluate(g=>g.collectionStore().getItems().every(n=>n.getAttr('state')==='VIC'))).toBe(true);
 await page.getByRole('button',{name:'Reload',exact:true}).click();
 await expect(page.locator('.example-live')).toContainText('8 states loaded');
 await expect.poll(()=>page.locator('gnr-grid').first().evaluate(g=>g.selectedKey)).toBe('VIC');
 await expect.poll(()=>page.locator('gnr-grid').first().evaluate(g=>g.collectionStore().metadata.totalrows)).toBe(8);
 const code=await page.locator('.cm-editor').innerText();
 expect(code).toContain('GenropyPage');
 expect(errors).toEqual([]);
});
