// Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setupDom} from '../js/dom/tests/dom.js';
setupDom();
const {Application, HtmlBuilder} = await import('gramlot-dom');
const {GramlotBuilder} = await import('../js/pages/src/builder.js');
const recipe = readFileSync(0, 'utf8');
let requests = 0;
globalThis.fetch = async url => { requests++; assert.match(String(url), /inspector.tytx$/); return {ok:true, text:async()=>recipe}; };
function page(options, Builder = GramlotBuilder) {
 const host = document.createElement('div'); document.body.append(host);
 class Example extends Builder { main(root) { root.div('Hello'); } }
 const builder = new Example('page');
 return new Application(host,builder,options);
}
const app = page();
assert.ok(app.inspector);
assert.equal(requests,0);
assert.equal(document.querySelector('gramlot-inspector'),null);
assert.equal(customElements.get('gramlot-inspector'),undefined);
const changes=[];
app.target.root.addEventListener('gramlot-inspector-change',e=>changes.push(e.detail.opened));
await app.inspector.open();
assert.equal(requests,1);
const component = app.inspector.element;
assert.equal(component.application,app);
assert.equal(component.tool.app.inspector,undefined,'internal application opts out');
assert.equal(component.shadowRoot.querySelector('[data-inspector="data"]').storeBag,app.builder.data);
assert.equal(component.shadowRoot.querySelector('[data-inspector="source"]').storeBag,app.builder.source);
assert.equal(app.inspector.opened,true);
assert.equal(changes.at(-1),true);
app.inspector.close();
assert.equal(changes.at(-1),false);
await app.inspector.open();
assert.equal(requests,1);
component.tool.app.live(()=>component.tool.app.builder.data.setItem('opened',false));
assert.equal(changes.at(-1),false,'palette close also announces state');
app.dispose();app.dispose();
assert.equal(component.tool.app._disposed,true);
assert.equal(document.querySelector('gramlot-inspector'),null);
const disabled=page({inspector:false});
assert.equal(disabled.inspector,undefined);
assert.equal(disabled.target.root.querySelector('button'),null);
disabled.dispose();
const plain=page({},HtmlBuilder);assert.equal(plain.inspector,undefined);plain.dispose();
globalThis.fetch = async () => ({ok:true,text:async()=>recipe});
const first = page(), second = page();
second.target.root.dispatchEvent(new window.KeyboardEvent('keydown', {
 key:'D',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true,
}));
await second.inspector.open();
assert.equal(first.inspector.element,null,'shortcut follows the application containing the event');
assert.equal(second.inspector.opened,true);
first.dispose();second.dispose();
globalThis.fetch = async url => {
 assert.match(String(url), /inspector-embedded.tytx$/);
 return {ok:true,text:async()=>process.env.INSPECTOR_EMBEDDED_SOURCE};
};
const embedded = page({inspector:{presentation:'embedded'}});
assert.equal(embedded.inspector.presentation,'embedded');
const embeddedEvents=[];
embedded.target.root.addEventListener('gramlot-inspector-change',event=>embeddedEvents.push(event.detail.opened));
await embedded.inspector.open();
const dock = embedded.inspector.element;
assert.equal(dock.getAttribute('presentation'),'embedded');
assert.equal(dock.shadowRoot.querySelector('gnr-palette'),null);
assert.ok(dock.shadowRoot.querySelector('gnr-tabcontainer'));
assert.equal(dock.hidden,false);
assert.equal(dock.shadowRoot.querySelector('[data-inspector="data"]').storeBag,embedded.builder.data);
embedded.inspector.close();assert.equal(dock.hidden,true);
await embedded.inspector.open();assert.equal(dock.hidden,false);
assert.deepEqual(embeddedEvents,[true,false,true]);
assert.throws(()=>{embedded.inspector.presentation='floating'},/before first opening/);
embedded.dispose();assert.equal(dock.isConnected,false);
const configured=page();configured.inspector.presentation='embedded';
await configured.inspector.open();assert.equal(configured.inspector.element.getAttribute('presentation'),'embedded');
configured.dispose();
const pending=page();
let finish, started;
const fetching = new Promise(resolve => { started = resolve; });
globalThis.fetch=()=>new Promise(resolve=>{finish=resolve;started();});
const opening=pending.inspector.open();
await fetching;
pending.dispose();
finish({ok:true,text:async()=>recipe});await opening;
assert.equal(pending.inspector.opened,false);
assert.equal(document.querySelector('gramlot-inspector'),null);
const theme=readFileSync(new URL('../js/pages/src/inspector-theme.css',import.meta.url),'utf8');
assert.match(theme,/light-dark/);assert.match(theme,/--gramlot-inspector-bg/);
console.log('Lazy inspector lifecycle, shared Bags, opt-out, visibility and theme contract passed');
