import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setupDom} from '../js/dom/tests/dom.js';
setupDom();
const {fromTytx}=await import('genro-tytx');
const {Application}=await import('gramlot-dom');
const {GramlotBuilder}=await import('../js/pages/src/builder.js');
const {mountInspector}=await import('../js/pages/src/inspector.js');
class Example extends GramlotBuilder {main(root){root.div('^amount');}}
const host=document.createElement('div'), tools=document.createElement('div');document.body.append(host,tools);
const page=new Application(host,new Example('page'),{inspector:false});
page.live(()=>{
 page.builder.data.setItem('amount',null,{dtype:'N',enabled:false,count:0,note:null,_meta:{test:'preserved'}});
 page.builder.data.setItem('flag',false,{dtype:'B'});
 page.builder.data.setItem('day',new Date('2026-09-09T00:00:00Z'),{dtype:'D'});
 page.builder.data.setItem('clock',new Date('1970-01-01T12:30:00Z'),{dtype:'H'});
});
const tool=mountInspector(tools,fromTytx(readFileSync(0,'utf8'),'json'),page);
const editor=tools.querySelector('[data-inspector="data-editor"]');
const cells=()=>editor.querySelector('[data-field="rows"]').shadowRoot;
const row=name=>[...cells().querySelectorAll('[data-property]')].find(r=>r.dataset.name===name);
const input=name=>row(name).querySelector('[data-cell="value"]');
const select=path=>tool.app.live(()=>tool.app.builder.data.setItem('dataPath',path));
const commit=(name,value,event='input')=>{const el=input(name);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new window.Event(event,{bubbles:true,composed:true}));el.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true,composed:true}));};
select('amount');
assert.equal(cells().querySelector('select'),null);
assert.equal(input('value').type,'number');
assert.equal(row('_meta'),undefined,'internal metadata is hidden');
assert.equal(input('enabled').type,'checkbox');
assert.equal(input('enabled').checked,false);
assert.equal(input('count').type,'number');
commit('enabled',true,'change');
assert.equal(page.builder.data.getItem('amount'),null,'editing an attribute preserves null');
assert.equal(page.builder.data.getNode('amount').attr.enabled,true);
assert.deepEqual(page.builder.data.getNode('amount').attr._meta,{test:'preserved'},'editing visible attributes retains metadata');
commit('value','0');assert.equal(page.builder.data.getItem('amount'),0);
commit('value','bad');assert.equal(page.builder.data.getItem('amount'),0,'invalid edit does not mutate');
assert.equal(editor.querySelector('[data-field="status"]').dataset.error,'true');
input('value').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Backspace',bubbles:true,cancelable:true}));
input('value').dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));
assert.equal(page.builder.data.getItem('amount'),null);
assert.equal(page.builder.data.getNode('amount').attr.dtype,'N');
editor.querySelector('[data-command="add"]').click();
const fresh=cells().querySelector('[data-fresh="true"]');
const newName=fresh.querySelector('[data-cell="name"]');newName.value='optionalCount';newName.dispatchEvent(new window.Event('input',{bubbles:true,composed:true}));
const choice=fresh.querySelector('select');choice.value='number';choice.dispatchEvent(new window.Event('change',{bubbles:true,composed:true}));
newName.dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));
assert.equal(page.builder.data.getNode('amount').attr.optionalCount,null);
assert.equal(fresh.querySelector('select'),null);
select('flag');select('amount');assert.equal(input('optionalCount').type,'number','new nullable attribute retains its selected type');
select('flag');assert.equal(input('value').type,'checkbox');commit('value',true,'change');assert.equal(page.builder.data.getItem('flag'),true);
input('value').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Backspace',bubbles:true,cancelable:true}));input('value').dispatchEvent(new window.FocusEvent('focusout',{bubbles:true}));
assert.equal(page.builder.data.getItem('flag'),null);assert.equal(input('value').indeterminate,true);
select('day');assert.equal(input('value').type,'date');commit('value','2026-10-12');assert.equal(page.builder.data.getItem('day').toISOString(),'2026-10-12T00:00:00.000Z');
select('clock');assert.equal(input('value').type,'time');commit('value','13:45');assert.equal(page.builder.data.getItem('clock').getUTCHours(),13);
page.dispose();
console.log('Typed inspector controls, dtype precedence, null, numbers, booleans, dates and invalid rollback passed');
