import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setupDom} from '../../gramlot-dom/tests/dom.js';
setupDom();
const {fromTytx} = await import('genro-tytx');
const {Bag} = await import('genro-bag-js');
const {mountInspector} = await import('../js/pages/src/inspector.js');
const host = document.createElement('div');
document.body.append(host);
const data = new Bag();
data.setItem('title', 'Original');
const source = new Bag();
source.setItem('node', 'Text');
const recipe = readFileSync(0, 'utf8');
const tool = mountInspector(host, fromTytx(recipe, 'json'), {builder:{data, source}});
assert.equal(host.querySelector('gnr-storetree').storeBag, data);
const key = extra => document.dispatchEvent(new window.KeyboardEvent('keydown', {
    key:'D', ctrlKey:true, shiftKey:true, bubbles:true, cancelable:true, ...extra}));
key({altKey:true});
assert.equal(tool.app.builder.data.getItem('opened'), false);
key();
assert.equal(tool.app.builder.data.getItem('opened'), true);
assert.equal(host.querySelector('gnr-storetree').storeBag, data);
host.querySelector('gnr-storetree').shadowRoot.querySelector('.leaf').click();
assert.match(host.querySelector('[data-inspector="data-detail"]').textContent, /Original/);
data.setItem('title', 'Changed');
assert.match(host.querySelector('[data-inspector="data-detail"]').textContent, /Changed/);
key({repeat:true});
assert.equal(tool.app.builder.data.getItem('opened'), true);
key();
assert.equal(tool.app.builder.data.getItem('opened'), false);
tool.app.live(() => tool.app.builder.data.setItem('dataPath', null));
tool.dispose();
key();
assert.equal(tool.app.builder.data.getItem('opened'), false);
console.log('Inspector: Python recipe, real Bag, selection, updates, shortcut and disposal passed.');
const disposedBefore = tool.app.data.toXml();
const next = mountInspector(host, fromTytx(recipe, 'json'), {builder:{data, source}});
host.querySelector('[data-inspector="toggle"]').click();
host.querySelector('gnr-storetree').shadowRoot.querySelector('.leaf').click();
assert.equal(next.app.builder.data.getItem('dataPath'), 'title');
assert.equal(tool.app.data.toXml(), disposedBefore, 'disposed inspector must not receive new widget events');
tool.dispose();
assert.ok(host.querySelector('gnr-storetree'), 'repeated old disposal must not remove the replacement');
next.dispose();
