import assert from 'node:assert/strict';
import {setupDom} from '../../gramlot-dom/tests/dom.js';
setupDom();
const {LabSession, CHANGE_CODE} = await import('../js/pages/src/lab-session.js');
const host = document.createElement('div');
document.body.appendChild(host);
let updates = 0;
const session = new LabSession(host, () => { updates++; });
assert.equal(host.querySelector('h2').textContent, 'Hello Genro');
session.run(CHANGE_CODE);
assert.equal(host.querySelector('h2').textContent, 'Hello Astra');
assert.match(session.app.builder.source.toXml(), /added/);
const input = host.querySelector('gnr-textbox').shadowRoot.querySelector('input');
input.value = 'Client edit';
input.dispatchEvent(new Event('change', {bubbles:true}));
assert.equal(session.app.builder.data.getItem('demo.title'), 'Client edit');
assert.equal(host.querySelector('h2').textContent, 'Client edit');
assert.throws(() => session.run('const ='), SyntaxError);
assert.throws(() => session.run('throw new Error("test")'), /test/);
session.reset();
assert.equal(host.querySelector('h2').textContent, 'Hello Genro');
assert.equal(host.querySelectorAll('h2').length, 1);
assert.ok(updates > 3);
console.log('Playground: build, mutation, writeback, errors, reset and Bag notifications passed.');
const {bagXmlView} = await import('../js/pages/src/bag-xml-view.js');
const before = session.app.builder.source.toXml();
const xml = bagXmlView(session.app.builder.source, 'source');
assert.ok(!xml.includes('[object Object]'));
assert.ok(xml.includes('&quot;'));
const parsed = new window.DOMParser().parseFromString(xml, 'application/xml');
assert.equal(parsed.querySelector('parsererror'), null);
assert.equal(typeof JSON.parse(parsed.querySelector('textBox').getAttribute('_meta')), 'object');
assert.equal(session.app.builder.source.toXml(), before);
assert.ok(bagXmlView(session.app.builder.data, 'data').startsWith('<data>'));
console.log('XML view: metadata JSON, valid XML, root and original Bag preserved.');
session.reset("root.textBox({value: 'Hello', lbl: 'Page title', color: 'red'});");
const colored = host.querySelector('gnr-textbox');
assert.equal(colored.style.color, 'red');
assert.equal(colored.getAttribute('lbl'), 'Page title');
assert.match(colored.shadowRoot.querySelector('style').textContent, /color: inherit/);
assert.equal(host.querySelectorAll('gnr-textbox').length, 1);
console.log('Rebuild replaces the recipe; textbox receives color and inherits it internally.');
const {mountPlayground} = await import('../js/pages/src/playground.js');
const lab = document.createElement('div');
document.body.appendChild(lab);
const {readFileSync} = await import('node:fs');
const {fromTytx} = await import('genro-tytx');
const {Application} = await import('gramlot-dom');
const {PlaygroundBuilder} = await import('../js/pages/src/playground-page.js');
const pageBuilder = new PlaygroundBuilder('main');
pageBuilder.loadSource(fromTytx(readFileSync(0, 'utf8'), 'json'));
const mounted = new Application(lab, pageBuilder);
const {ui, session: experiment} = await mountPlayground(lab, mounted);
assert.equal(lab.querySelectorAll('gnr-codemirror').length, 3);
assert.match(ui.builder.source.toXml(), /codeMirror/);
const previewNode = lab.querySelector('[data-lab="lab-preview"]');
lab.querySelector('[data-lab="lab-example"]').click();
assert.match(lab.querySelector('[data-lab="lab-code"]').value, /Hello Astra/);
lab.querySelector('[data-lab="lab-apply"]').click();
assert.equal(previewNode.querySelector('h2').textContent, 'Hello Astra');
assert.equal(lab.querySelector('[data-lab="lab-preview"]'), previewNode);
lab.querySelector('[data-lab="lab-reset"]').click();
assert.equal(previewNode.querySelector('h2').textContent, 'Hello Genro');
assert.match(ui.builder.data.getItem('dataXml'), /Hello Genro/);
console.log('Laboratory UI is built from SourceBag; controls, editors and XML use its data bindings.');
const liveInput = previewNode.querySelector('gnr-textbox').shadowRoot.querySelector('input');
liveInput.value = 'Nested edit';
liveInput.dispatchEvent(new Event('change', {bubbles: true}));
assert.equal(experiment.app.builder.data.getItem('demo.title'), 'Nested edit');
const autoInput = lab.querySelector('[data-lab="lab-auto"]').shadowRoot.querySelector('input');
autoInput.checked = true;
autoInput.dispatchEvent(new Event('change', {bubbles: true}));
assert.equal(ui.builder.data.getItem('auto'), true);
experiment.reset("data.setItem('page', 'first'); const tabs = root.tabContainer({selectedPage: '^page'}); tabs.contentPane({pageName: 'first', title: 'First'}); tabs.contentPane({pageName: 'second', title: 'Second'});");
previewNode.querySelector('gnr-tabcontainer').shadowRoot.querySelector('[data-key="second"]').click();
assert.equal(experiment.app.builder.data.getItem('page'), 'second');
assert.equal(ui.data.getItem('experiment.page'), null, 'preview commands must stay in their owning Application');
