# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""Authoring grammar for the current client collections in the test laboratory."""
from genro_builders.builder import element
from genro_builders.contrib.html.html_builder import HtmlBuilder


class WidgetTestBuilder(HtmlBuilder):
    # GUI spelling; generic HTML keeps its native data element.
    data_recipe_alias = True

    @element(_meta={"data_element": True})
    def dataFormula(self, destination: str, formula: str, **kwargs): ...

    @element(sub_tags="*")
    def form(self, **kwargs): ...

    @element(sub_tags="*")
    def labledBox(self, **kwargs): ...

    @element(sub_tags="")
    def copyButton(self, **kwargs): ...

    @element(sub_tags="*")
    def palette(self, **kwargs): ...

    @element(sub_tags="")
    def codeMirror(self, **kwargs): ...

    @element(sub_tags="summary,div")
    def details(self, **kwargs): ...

    @element(sub_tags="*")
    def div(self, **kwargs): ...

    @element(sub_tags="")
    def textBox(self, **kwargs): ...

    @element(sub_tags="")
    def filteringSelect(self, **kwargs): ...

    @element(sub_tags="")
    def comboBox(self, **kwargs): ...

    @element(sub_tags="")
    def passwordbox(self, **kwargs): ...

    @element(sub_tags="")
    def numberTextBox(self, **kwargs): ...

    @element(sub_tags="")
    def dateTextBox(self, **kwargs): ...

    @element(sub_tags="")
    def timeTextBox(self, **kwargs): ...

    @element(sub_tags="")
    def horizontalSlider(self, **kwargs): ...

    @element(sub_tags="")
    def verticalSlider(self, **kwargs): ...

    @element(sub_tags="")
    def checkbox(self, **kwargs): ...

    @element(sub_tags="*")
    def formlet(self, **kwargs): ...

    @element(sub_tags="*")
    def panel(self, **kwargs): ...

    @element(sub_tags="*")
    def box(self, **kwargs): ...

    @element(sub_tags="*")
    def borderContainer(self, **kwargs): ...

    @element(sub_tags="*")
    def tabContainer(self, **kwargs): ...

    @element(sub_tags="*")
    def stackContainer(self, **kwargs): ...

    @element(sub_tags="*")
    def contentPane(self, **kwargs): ...

    @element(sub_tags="")
    def stackButtons(self, **kwargs): ...

    @element(sub_tags="*")
    def tab(self, **kwargs): ...

    @element(sub_tags="")
    def colorpicker(self, **kwargs): ...

    @element(sub_tags="")
    def storeTree(self, **kwargs): ...
