# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""Generate alpha component declarations from explicitly selected trusted JSON.

Default: the framework catalogue. No module execution or package scanning.
External packages can pass --source, --javascript and --python-directory.
"""
from __future__ import annotations
import argparse
import json
import keyword
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUP_FILES = {'InputDeclarations':'inputs.py', 'LayoutDeclarations':'layout.py',
               'DecorationDeclarations':'decoration.py', 'FormDeclarations':'forms.py',
               'AdjacentWidgetDeclarations':'widgets.py'}


def generate(source, javascript, python_directory):
    catalog = json.loads(source.read_text())
    if catalog.get('schema') != 'gramlot-components/0.1':
        raise ValueError('Unsupported component schema')
    groups = {}; seen = set(); collection_names = set()
    for collection in catalog['collections']:
        if collection['name'] in collection_names: raise ValueError('Duplicate collection')
        collection_names.add(collection['name'])
        for item in collection['components']:
            name = item['name']; group = item['pythonGroup']
            if not name.isidentifier() or keyword.iskeyword(name) or name in seen:
                raise ValueError(f'Invalid or duplicate declaration: {name}')
            if not group.isidentifier() or keyword.iskeyword(group): raise ValueError('Invalid declaration class')
            if not re.fullmatch(r'[a-z][a-z0-9]*(?:-[a-z0-9]+)+', item['tag']):
                raise ValueError('Invalid custom-element tag')
            if not isinstance(item.get('subTags', ''), str): raise ValueError('subTags must be a string')
            seen.add(name); groups.setdefault(group, []).append(item)
    # Existing optional editor lives in pages; keep its declaration in the same
    # generated adjacent family, described by the selected catalogue too.
    javascript.parent.mkdir(parents=True, exist_ok=True)
    javascript.write_text('// Generated by scripts/generate_components.py; do not edit.\n'
                          'export const BUILTIN_COMPONENTS = '+json.dumps(catalog['collections'], indent=2)+';\n'
                          'export function builtinComponents(name) {\n'
                          '    const collection = BUILTIN_COMPONENTS.find(item => item.name === name);\n'
                          '    if (!collection) throw new Error(`Unknown component collection: ${name}`);\n'
                          '    return collection.components;\n}\n')
    python_directory.mkdir(parents=True, exist_ok=True)
    for group, items in groups.items():
        lines = ['# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0',
                 '# Generated by scripts/generate_components.py; do not edit.',
                 'from genro_builders.builder import element', '', '', f'class {group}:',
                 '    """Alpha component declarations; runtime owns values and binding."""']
        for item in items:
            lines += ['', f'    @element(sub_tags={item.get("subTags", "")!r}, _meta={dict(item.get("meta", {}), webcomponent=True, render_tag=item["tag"])!r})',
                      f'    def {item["name"]}(self, **kwargs): ...']
        (python_directory / GROUP_FILES.get(group, group+'.py')).write_text('\n'.join(lines)+'\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT/'js/dom/src/components/builtin-components.json')
    parser.add_argument('--javascript', type=Path, default=ROOT/'js/dom/src/components/builtin-components.js')
    parser.add_argument('--python-directory', type=Path, default=ROOT/'src/gramlot/grammar')
    args = parser.parse_args()
    generate(args.source, args.javascript, args.python_directory)
