# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""Generate alpha component declarations from explicitly selected trusted JSON.

Default: the framework catalogue. No module execution or package scanning.
External packages can pass --source, --javascript and --python-directory.
"""
from __future__ import annotations
import argparse
import json
import keyword
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUP_FILES = {'InputDeclarations':'inputs.py', 'LayoutDeclarations':'layout.py',
               'DecorationDeclarations':'decoration.py', 'FormDeclarations':'forms.py',
               'AdjacentWidgetDeclarations':'widgets.py'}


def generate(source, javascript, python_directory, documentation=None):
    catalog = json.loads(source.read_text())
    if catalog.get('schema') != 'gramlot-components/0.1':
        raise ValueError('Unsupported component schema')
    groups = {}; seen = set(); collection_names = set()
    for collection in catalog['collections']:
        if collection['name'] in collection_names: raise ValueError('Duplicate collection')
        collection_names.add(collection['name'])
        for item in collection['components']:
            name = item['name']; group = item['pythonGroup']
            if not name.isidentifier() or keyword.iskeyword(name) or name in seen:
                raise ValueError(f'Invalid or duplicate declaration: {name}')
            if not group.isidentifier() or keyword.iskeyword(group): raise ValueError('Invalid declaration class')
            if not re.fullmatch(r'[a-z][a-z0-9]*(?:-[a-z0-9]+)+', item['tag']):
                raise ValueError('Invalid custom-element tag')
            if not isinstance(item.get('subTags', ''), str): raise ValueError('subTags must be a string')
            seen.add(name); groups.setdefault(group, []).append(item)
    # Existing optional editor lives in pages; keep its declaration in the same
    # generated adjacent family, described by the selected catalogue too.
    javascript.parent.mkdir(parents=True, exist_ok=True)
    javascript.write_text('// Generated by scripts/generate_components.py; do not edit.\n'
                          'export const BUILTIN_COMPONENTS = '+json.dumps(catalog['collections'], indent=2)+';\n'
                          'export function builtinComponents(name) {\n'
                          '    const collection = BUILTIN_COMPONENTS.find(item => item.name === name);\n'
                          '    if (!collection) throw new Error(`Unknown component collection: ${name}`);\n'
                          '    return collection.components;\n}\n')
    python_directory.mkdir(parents=True, exist_ok=True)
    for group, items in groups.items():
        lines = ['# Copyright 2026 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0',
                 '# Generated by scripts/generate_components.py; do not edit.',
                 'from genro_builders.builder import element', '', '', f'class {group}:',
                 '    """Alpha component declarations; runtime owns values and binding."""']
        for item in items:
            meta = dict(item.get('meta', {}), webcomponent=True, render_tag=item['tag'])
            for key in ('docline', 'parameters', 'serverRequired', 'providerRequest', 'providerResponse', 'examples', 'notes'):
                if key in item:
                    meta[key] = item[key]
            lines += ['', f'    @element(sub_tags={item.get("subTags", "")!r}, _meta={meta!r})']
            if item.get('docline'):
                lines += [f'    def {item["name"]}(self, **kwargs):', f'        {item["docline"]!r}', '        ...']
            else:
                lines += [f'    def {item["name"]}(self, **kwargs): ...']
        (python_directory / GROUP_FILES.get(group, group+'.py')).write_text('\n'.join(lines)+'\n')
    if documentation is not None:
        lines = ['.. Generated by scripts/generate_components.py; do not edit.', '',
                 'Documented components', '=====================', '',
                 'Current development implementation. Metadata and examples below come from',
                 'the component catalogue; they are not a promise of full legacy compatibility.', '']
        for collection in catalog['collections']:
            for item in collection['components']:
                if not item.get('docline'):
                    continue
                lines += [item['name'], '-' * len(item['name']), '', item['docline'], '',
                          f'Collection: ``{collection["name"]}``. Tag: ``{item["tag"]}``.', '',
                          'Server required: ' + ('yes.' if item.get('serverRequired') else 'no.'), '',
                          'Child tags: ' + (item.get('subTags') or 'none.') , '']
                for key, title in [('parameters', 'Parameters'), ('providerRequest', 'Provider request'), ('providerResponse', 'Provider response')]:
                    lines += [title, '~' * len(title), '']
                    for parameter in item.get(key, []):
                        default = json.dumps(parameter['default'])
                        status = 'required' if parameter['required'] else 'optional'
                        lines += [f'* ``{parameter["name"]}`` — {parameter["type"]}; {status}; default: ``{default}``.',
                                  '', '  ' + parameter['docline'], '']
                lines += ['Behavior and limits', '~~~~~~~~~~~~~~~~~~~', '']
                for note in item.get('notes', []):
                    lines += ['* ' + note, '']
                for example in item.get('examples', []):
                    lines += [example['title'], '~' * len(example['title']), '',
                              f'.. code-block:: {example["language"]}', '']
                    lines += [('   ' + line) if line else '' for line in example['code'].splitlines()] + ['']
        documentation.parent.mkdir(parents=True, exist_ok=True)
        documentation.write_text('\n'.join(lines))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT/'js/dom/src/components/builtin-components.json')
    parser.add_argument('--javascript', type=Path, default=ROOT/'js/dom/src/components/builtin-components.js')
    parser.add_argument('--python-directory', type=Path, default=ROOT/'src/gramlot/grammar')
    parser.add_argument('--documentation', type=Path, help='Generate the documented component reference as reStructuredText')
    args = parser.parse_args()
    generate(args.source, args.javascript, args.python_directory, args.documentation)
